### ISSUE TITLE
pick_ik not found in loaded plugin descriptions

### ISSUE THREAD

**Issue by philip-n** [PickNikRobotics/pick_ik#32] opened 2023-02-20 18:02 UTC
First, thanks for creating this solver! It sounds like it matches very well with what I'm looking for and I'm looking forward to test it!

I just cloned the repository and compiled via `colcon build --mixin release`. According to colcon, this works just fine: `Finished <<< pick_ik [57.7s]`. I then sourced the `install/setup.bash`. `ros2 pkg list` now lists `pick_ik` as expected.

To kickstart things, I copied the example from the [USAGE.md]
\(https://github.com/PickNikRobotics/pick_ik/blob/main/doc/USAGE.md). My current `kinematics.yaml` looks like this:

```yaml
/**:
  ros__parameters:
    robot_description_kinematics:
      ur_manipulator:
        # kinematics_solver: kdl_kinematics_plugin/KDLKinematicsPlugin
        # kinematics_solver_search_resolution: 0.005
        # kinematics_solver_timeout: 0.005
        # kinematics_solver_attempts: 3
        kinematics_solver: pick_ik/PickIkPlugin
        kinematics_solver_timeout: 0.5
        kinematics_solver_attempts: 3
        mode: local
        rotation_scale: 0.5
        position_threshold: 0.001
        orientation_threshold: 0.01
        cost_threshold: 0.001
        minimal_displacement_weight: 0.0
        gd_step_size: 0.0001
```

However, when launching this via `ros2 launch ur_moveit_config ur_moveit.launch.py ur_type:=ur10e launch_rviz:=true use_fake_hardware:=true`, I get the following error:

```
[move_group-1] [ERROR] [1676915114.700383194] [kinematics_plugin_loader]: The kinematics plugin (ur_manipulator) failed to load. Error: According to the loaded plugin descriptions the class pick_ik/PickIkPlugin with base class type kinematics::KinematicsBase does not exist. Declared types are  cached_ik_kinematics_plugin/CachedKDLKinematicsPlugin cached_ik_kinematics_plugin/CachedSrvKinematicsPlugin kdl_kinematics_plugin/KDLKinematicsPlugin lma_kinematics_plugin/LMAKinematicsPlugin srv_kinematics_plugin/SrvKinematicsPlugin
[move_group-1] [ERROR] [1676915114.700481005] [moveit_ros.robot_model_loader]: Kinematics solver could not be instantiated for joint group ur_manipulator.
```

*(this is actually reported twice, once for the `move_group` and once for `rviz`)*.

Unfortunately, I'm not really familiar with ROS2 yet, so I don't know where / how to start troubleshooting. I'm using ROS Humble, so the `rospack plugin ...` command that is referred to in some older tutorials is not available (and I'm not sure if it would be helpful).

Any ideas and suggestions on what causes this and how to solve it would be much appreciated!

**Comment by tylerjw** [comment] 2023-02-20 18:11
That is weird, I'll see if I can reproduce this. Are you doing this on humble or rolling?

**Comment by philip-n** [comment] 2023-02-20 18:31
Thanks for the quick reply!

I'm on Humble, in a docker container. `humble-source` from https://hub.docker.com/r/moveit/moveit2/tags (probably not updated since 3 weeks or so).

**Comment by sea-bass** [comment] 2023-02-20 19:13
I saw this happening to me recently as well, and it did work if I had the package actually introduce an <exec_depends> on `pick_ik`, and was as well included in the `CMakeLists.txt`.

Didn't probe into this further myself yet. But are there any limitations in having the IK plugins be accessible by a package that doesn't explicitly depend on it?

**Comment by sea-bass** [comment] 2023-02-21 15:28
To follow up on this, @philip-n , if you modify the `package.xml` in the `ur_moveit_config` package to add this line, does the plugin load fine?

```
<exec_depend>pick_ik</exec_depend>
```

**Comment by philip-n** [comment] 2023-02-21 16:03
I saw your comment yesterday and did exactly that, and it works great. Then I started to play around with `pick_ik` until very late and totally forgot to provide feedback. Sorry!

As you mentioned in an earlier comment, not having to do this would be great in general (I always like to keep packages pristine, if possible). But my problem is solved - do you want me to close this issue or keep it open for follow-up (e.g. docs)?

**Comment by sea-bass** [comment] 2023-02-25 13:09
Thanks for confirming, and that you're unblocked for now.

I'd say keep it open while I figure out the root cause, or if it's just expected behavior, and I'll get back to this.

**Comment by sea-bass** [comment] 2023-09-22 02:43
Coming back to this... I think this is expected with plugins, so will close this issue.

**Closed by sea-bass** 2023-09-22 02:43 UTC
