### ISSUE TITLE
pick_ik ignores joint limits

### ISSUE THREAD

**Issue by SammyRamone** [PickNikRobotics/pick_ik#43] opened 2023-05-31 09:31 UTC
The `pick_ik` provides solutions which are not respecting the joint limits. Of course, it is possible to provide a custom function to the `setFromIK()` call which checks if the solution is valid (e.g. by calling the` statisfiesBounds()` method on the robot state).
However, I think that `pick_ik` should do it automatically. Other MoveIt IK solvers that I used before only provided solutions which satisfy the joint limits. Therefore, it was quiet unexpected behavior which lead to some confusion.
I know that there is also the `avoid_joint_limits_weight` which can be used, but this generally avoids the limits and does not only do a binary check if the solution is inside the limits.

To show the difference to the behavior of other IK solvers, I will provide a small example from the demo of the [reach_ros2 ](https://github.com/ros-industrial/reach_ros2)package. The goal of this demo is to check if the robot can reach each of the shown markers.
This is the solution when using pick_ik without futher checks. It will provide some solutions which go over joint limits.
![pick_ik_nocheck](https://github.com/PickNikRobotics/pick_ik/assets/11520148/e7776f23-0256-4206-a25e-9fc40b23ddff)

If a manual check for joint limits is introduced, it will not find a solution for this point (shown by a black marker and the arm being in zero pose).
![pick_ik_check](https://github.com/PickNikRobotics/pick_ik/assets/11520148/89412ac0-5b36-47cb-afdc-a36705a06b63)

The same behavior is also done by the KDL plugin.
![kdl](https://github.com/PickNikRobotics/pick_ik/assets/11520148/6ed8eb16-7b92-46e4-aa38-d8c91c5ab880)

As well as by the original bio_ik plugin.
![bio_ik](https://github.com/PickNikRobotics/pick_ik/assets/11520148/810eeef6-5d53-43b7-b595-81d6777d6439)

I think it would make sense to follow the same behavior as other MoveIt IK solvers and I also don't see any benefit of getting IK solutions which are not respecting the joint limits.
Additionally, the current behavior also leads to the MoveIt demo.launch being not so useful, as one can not so simply add an additional check in there.

**Comment by sea-bass** [comment] 2023-05-31 12:34
I agree. If `pick_ik` is not respecting joint limits, that's a bug and certainly not intended behavior.

Both the [local solver](https://github.com/PickNikRobotics/pick_ik/blob/main/src/ik_gradient.cpp#L81-L83) and [global solver](https://github.com/PickNikRobotics/pick_ik/blob/main/src/ik_memetic.cpp#L162) are supposed to clamp to joint limits, so either there is a bug in this logic or in parsing the joint limits from the robot model. We'll take a look.

Unrelated, I was just talking to my colleagues about the Reach benchmarks and we might soon start collecting benchmark data to compare the solvers quantitatively. Glad to see that it's as easy as swapping out the kinematics.yaml file.

**Comment by Robotawi** [comment] 2023-06-03 12:45
Thanks for reporting this issue, @SammyRamone!
I have successfully reproduced the issue using `reach_ros2` and `pick_ik` as a solver. I will check the source code where the limits checking is performed to find the cause.

Here is a pose in which `joint_l` and `joint_b` were violated. Both have a range from `-1.9198` to `1.9198`.
![violated joints screenshot](https://github.com/PickNikRobotics/pick_ik/assets/9701369/cb20b517-838f-4404-b457-71ab47834580)

Here are the out-of-range joint values 
![violated joints values screenshot](https://github.com/PickNikRobotics/pick_ik/assets/9701369/b67078e5-66f5-4ce5-a04b-62f665edfb98)

**Comment by sea-bass** [comment] 2023-06-03 16:24
@Robotawi thanks for looking into this. I have a few tips for where to look for the bug:

1. In `pick_ik`'s [robot model parsing](https://github.com/PickNikRobotics/pick_ik/blob/main/src/robot.cpp#L35-L43), put some breakpoints/debug statements to see if the joint limits given to the joint as correct. If it's wrong here, then we can localize the bug to that.
2. Otherwise, try setting the `mode` parameter of the solver to `local` first. If you can recreate the issue above just by using the local solver, then the issue is [somewhere here](https://github.com/PickNikRobotics/pick_ik/blob/main/src/ik_gradient.cpp#L81-L83).
3. Lastly, you can look at the [global solver](https://github.com/PickNikRobotics/pick_ik/blob/main/src/ik_memetic.cpp#L162) code.

**Comment by Robotawi** [comment] 2023-06-15 12:23
@sea-bass, I want to share an update on my progress in debugging the issue of out-of-range joint values. Although I haven't fully identified the cause yet, I have taken some steps to isolate the problem and would appreciate any further insights. I am using [this branch](https://github.com/Robotawi/pick_ik/tree/debug/out-of-range-joints) for debugging. 

(1) I verified the parsing step and the joint limits are correctly parsed. They match the joints in the arm's `xacro` file.

(2) I switched the optimizer to `local` mode and began examining the gradient descent-related parts.

(3) I looked into the [applying optimization step](https://github.com/PickNikRobotics/pick_ik/blob/3b5cc04a3e99d6a5323c2bdcd2a9835046adad4f/src/ik_gradient.cpp#L78) and observed that the calculated new joint value, given by `self.local[i] - self.gradient[i] * joint_diff` can exceed the joint limits. These cases are clamped to the `clip_min` or `clip_max` limits. Although this shows the joint values stay within the allowable range, I do not think it is desirable to call the cost functions with those clamped min/max values. Please correct me if I am wrong. 

(4) I checked the process of [computing the gradient direction](https://github.com/PickNikRobotics/pick_ik/blob/3b5cc04a3e99d6a5323c2bdcd2a9835046adad4f/src/ik_gradient.cpp#L27), which involves checking the negative and positive displacements. I found that in some cases, the gradient can be computed with values that are out-of-range. I mean that `self.working[i] = self.local[i] - step_size` and `self.working[i] = self.local[i] + step_size` can actually go beyond the joint ranges. This results in `p1 = cost_fn(self.working)` and `p3 = cost_fn(self.working)` be calculated based on out-of-range values. This suggests clamping the `self.working` joint values and decreasing the `step_size` parameter. I clamped the joints in the code, and decreased the `step_size` in the `kinematics.yaml` file, but the issue of out-of-range solutions persisted. **Should we consider adjustments to the cost function or further investigate the gradient computation?** 

(5) To validate the `[initial_guess](https://github.com/PickNikRobotics/pick_ik/blob/3b5cc04a3e99d6a5323c2bdcd2a9835046adad4f/src/ik_gradient.cpp#LL14C1-L14C1)` joint values, I modified the code to pass a reference to a robot object to the `GradientIk::from` function. I noticed that sometimes the initial guess joint values exactly matches the `clip_min` or `clip_max` values without exceeding these limits. Approximately, this happens 50 times per 1000 calls. **I do not think this is the intended behavior.** This will probably slow convergence. **Does this suggest any additional area to debug or something to modify?**

(6) I have also checked the active positions in the `[make_is_solution_test_fn](https://github.com/Robotawi/pick_ik/blob/b34816257a8d4516e7905b66ffcbd251b09d68f6/src/goal.cpp#L165)` function before it returns `true` indicating an acceptable solution and did not catch the out-of-range joints. I set it to return `false` when a value equal to the joint limits is checked, but did not eliminate the problem.

(7) Finally, I tightened the `position_threshold`, `orientation_threshold`, and `cost_threshold` values. The number of out-of-range solutions decreased but was not zero. 

I want also to confirm that I tried with KDL IK solver, and it did not result in any out-of-range joint values, so it is for sure something on our side.

Sorry, I could not find exactly where the issue is, but I look forward to any guidance you might have for resolving this issue. I have not understood some of the details but I will continue trying to comprehend more and find the root cause. Feel free to suggest to me where to look or re-visit any parts. Thank you!

**Comment by sea-bass** [comment] 2023-06-15 12:53
Thanks for this detailed analysis, @Robotawi !

I think there are some good improvements to be made here based on this, but I wanted to maybe check if https://github.com/PickNikRobotics/pick_ik/pull/48 could affect this? What happens if you include the changes in here?

**Comment by Robotawi** [comment] 2023-06-19 14:35
With pleasure, @sea-bass. I will keep trying till we figure it out. I checked the cost functions implemented in `goal.cpp` and want to add a cost function for your mentioned purpose. However, I need clarification about how to incorporate a function that operates from inside the gradient_descent calculation. Your guidance for the implementation would be greatly appreciated.

FYI, the out-of-range joints issue persists despite PR #48, and setting the `avoid_joint_limits_weight` causes the IK solution to fail. In terms of the `reach` study, the reachability becomes zero. Here is a sample of the output.
```
[reach_ros_node-1] Reach study complete
[reach_ros_node-1] Starting optimization
[reach_ros_node-1] Entering optimization loop 0
[reach_ros_node-1] 
[reach_ros_node-1] 0%   10   20   30   40   50   60   70   80   90   100%
[reach_ros_node-1] |----|----|----|----|----|----|----|----|----|----|
[reach_ros_node-1] ***************************************************
[reach_ros_node-1] ------------------------------------------------
[reach_ros_node-1] Percent Reached = 0
[reach_ros_node-1] Total points score = 0
[reach_ros_node-1] Normalized total points score = -nan
```

This is the `kinematics.yaml config file with the `avoid_joint_limits_weight` param, which was used when I got the previous result.

```
manipulator:
  kinematics_solver: pick_ik/PickIkPlugin
  kinematics_solver_timeout: 0.05
  kinematics_solver_attempts: 3
  mode: global
  position_scale: 1.0
  rotation_scale: 0.5
  position_threshold: 0.001
  orientation_threshold: 0.01
  avoid_joint_limits_weight: 0.001
  cost_threshold: 0.001
  minimal_displacement_weight: 0.0
  gd_step_size: 0.0001
```
___
I have a question. When the `SolutionTestFn` returns `true`, which means `frame_tests` and `goals` are satisfied, where after this check should I focus to see what may be causing the issue?

**Comment by sea-bass** [comment] 2023-06-24 13:11
So, I just tested and wasn't able to reproduce this...

![image](https://github.com/PickNikRobotics/pick_ik/assets/4603398/39480efb-ccdd-4499-9fd8-467807695e8d)

I just switched the `kinematics.yaml` in the demo to use `pick_ik` and ran it... am I missing anything else?

**Comment by sea-bass** [comment] 2023-06-24 13:43
OK yeah, I'm not able to reproduce the problem. On the latest branch I get no out of bounds solutions...

![image](https://github.com/PickNikRobotics/pick_ik/assets/4603398/fe2e12c2-f88d-4cf0-b416-5d0fefaa0943)

**Comment by sea-bass** [comment] 2023-06-24 14:24
WOW I think I found the issue... `pick_ik` is alphabetizes the joint names, so the limits are out of order because this particular model uses letters instead of numbers for the joint names.

If I hard-code the order of the joints, the dead spot correctly comes up... now to make this generic to all robot models. Time to go dumpster diving in the MoveIt API.

![image](https://github.com/PickNikRobotics/pick_ik/assets/4603398/4eb355f2-1c15-4ada-b69d-5ae70af6b0e5)

**Comment by sea-bass** [comment] 2023-06-24 14:38
Can you guys try to test with this PR branch? https://github.com/PickNikRobotics/pick_ik/pull/54

**Comment by Robotawi** [comment] 2023-06-26 12:53
The change fixes the out-of-bounds joint issue. Thank you, @sea-bass! :+1: :tada:

**Closed** 2023-06-26 12:57 UTC
